services:
  rocky10run:
    build:
      context: .
      args:
        rocky: $RL10
    image: "aursu/php84build:${RL10TAG}-runtime"
  rocky10devbase:
    build:
      context: .
      args:
        image: node22dev
        rocky: $RL10
    image: "aursu/php84build:${RL10TAG}-devbase"

